include: package:very_good_analysis/analysis_options.7.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    avoid_catches_without_on_clauses: ignore
    one_member_abstracts: ignore
  exclude: [build/**, lib/**.freezed.dart, lib/**.g.dart, "lib/l10n/**"]
